### PR TITLE
[Doctrine] Skip Collection<int, object> on ImproveDoctrineCollectionDocTypeInEntityRector

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7006
Fixes https://github.com/rectorphp/rector/issues/6988

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
