### PR TITLE
[Set] Replace addOrderBy order with a constant

### PR DESCRIPTION
**Pull request by wkania**
There is _orderBy_ so I added _addOrderBy_ with some tests.

### CODE REVIEW

**Comment by wkania** [comment]
Hi @TomasVotruba

> First-time contributors need a maintainer to approve running workflows.

**Comment by samsonasik** [comment]
Workflow approved

**Comment by wkania** [comment]
@samsonasik Thank you. The PHPStan errors are not related to my changes.

**Comment by TomasVotruba** [comment]
@wkania The PHPStan errors are fixed in https://github.com/rectorphp/rector-doctrine/pull/30, please rebase on new `main`

**Comment by wkania** [comment]
@TomasVotruba rebased

**Comment by TomasVotruba** [comment]
Thank you ☺️

**Comment by wkania** [comment]
@TomasVotruba Oh no, another not related PHPStan error.

**Comment by TomasVotruba** [comment]
No worries :slightly_smiling_face: Let's merge it as it is :+1:

**Pull request merged**
