### PR TITLE
Use StringNode

### PR DESCRIPTION
**Pull request by yguedidi**

### CODE REVIEW

**Comment by yguedidi** [comment]
@TomasVotruba please check this :)

**Comment by TomasVotruba** [comment]
Great job :)

**Comment by yguedidi** [comment]
@TomasVotruba what are the next steps? should this be merged with my repo as source for rector-src and them update the package in the PR on rector-src side? or should I update the PR on rector-src to use my repos for packages? :)

**Comment by TomasVotruba** [comment]
There should be an opened PR to all packages. Then you can require specific branch in rector-src for each package.

E.g. update `dev-main` to `dev-yguedidi:use-stringnode` on this line in your PR on rector-src: https://github.com/rectorphp/rector-src/blob/cc3354aa8e764fd028f5de5ac1fb76e9304bdbbd/composer.json#L27

When the CI will run test on rector-doctrine package there, they should pass :)

**Comment by yguedidi** [comment]
@TomasVotruba did the update in composer in https://github.com/rectorphp/rector-src/pull/3645 but still packages tests don't pass because of https://github.com/rectorphp/rector-src/blob/main/.github/workflows/packages_tests.yaml#L55
What should I do? update the workflow file?

**Comment by yguedidi** [comment]
@TomasVotruba see that tests are green here :)

Note that in order to make it appear green, I had to make use of my fork as a source repository for rector-src to use the branch introducing `StringNode`
Note also that it uses a version of the branch without [the commit that makes the CI green on rector-src](https://github.com/rectorphp/rector-src/pull/3645/commits/45cac294d8fc12dd2eee7e39b656a74e57df7b6f) (see [the revert commit after](https://github.com/rectorphp/rector-src/pull/3645/commits/46e41394e71c39ead19e212cb2f1df20fa4095d4)) because otherwise vendors will not install because of a circular dependency:
- this PR needs rector-src fork with `StringNode`
- rector-src PR needs this PR to have its package tests pass

**Comment by TomasVotruba** [comment]
Merged in https://github.com/rectorphp/rector-doctrine/pull/174, thanks :+1:

**Pull request closed without merging**
