### PR TITLE
[Doctrine] Add boolean type on TypedPropertyFromColumnTypeRector

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7157

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉 /cc @Lenny4

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
I am merging it ;)

**Review by TomasVotruba — COMMENTED** [review]
👍

**Pull request merged**
