### PR TITLE
[NodeManipulator] Fix PHPStan notice on ToOneRelationPropertyTypeResolver

### PR DESCRIPTION
**Pull request by samsonasik**
see https://github.com/rectorphp/rector-src/actions/runs/5777190561/job/15657084415?pr=4676#step:7:16

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by samsonasik** [comment]
This is strange that this change not included in build scoper

https://github.com/rectorphp/rector/commit/9165e88cea56cdd458d90f6441f620619800c977#diff-d449917afbb005d5b114cf1e65bb45234b614f728e1eca0af46393d093e8178e

**Comment by TomasVotruba** [comment]
I think it will need some trigger on the main build

**Comment by samsonasik** [comment]
It seems not included even with manual trigger https://github.com/rectorphp/rector/commit/c3e12c8e9c34da1ca1fa3e96de5656c58fc6dc82

**Pull request merged**
