### PR TITLE
not/nullable join-column in toone relation

### PR DESCRIPTION
**Pull request by jirinapravnik**
I tried to solved resolving of nullable value in toone relations for PHP Attributes.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the PR :+1:  I wanted to go for merge now, but I could not find any test fixture that is added to verify it works.

Could you add it? I'll resolve this one promptly then

**Comment by TomasVotruba** [comment]
cc @samsonasik How about this one, can be closed as well?

**Comment by samsonasik** [comment]
Yes, this can be closed. nullable on typed property is always a safe belt for migration on unitialized property, even user define `nullable: false`, it still can be nullable in real DB afaik.

**Comment by jirinapravnik** [comment]
If you have null in the DB and nullable:false in ORM, you have invalid metadata And you should fix that. I thought Rector is for making quality code not for  supporting od code smell. Same thing with non-nullable columns in the other issues. But I understand your project  your decision.

**Comment by samsonasik** [comment]
We learned the hard way in the past for converting non-typed property to typed property rely by docblock.

On migrating code, on small code, that's probably easy to patch, for big code base, you will end up multiple patch.

That's why the rule need to be configurable, we already discuss about it on your other PR, if you don't have time to finish configurable rule, you can create your own custom rule yourself for your needs.

**Comment by jirinapravnik** [comment]
I couldn't know that this rule should be configurable, since in this PR there was no such requirement. It looks similar to #191, but ORM\Column is nullable: false by default, but ORM\JoinColumn nullable:true by default and you must explicitly tell, that it is non-nullable.

I have made configurable rule in the other PR (#191) . But later the maintainers made changes and also removed the interface, which I used for configuring and I would have to change it again. I felt, It would be a waste of my time.

**Pull request closed without merging**
