### PR TITLE
Refactor YamlToAttributeDoctrineMappingRector to use attributes as more reliable

### PR DESCRIPTION
**Pull request by TomasVotruba**
The old annotations required many extra checks, and were causing troubles on nested annotations.
Instead of doing this 2-step jump, we can use native attributes instead :+1: 

Upgrade to PHP 8.1, then use this rule to handle your yaml configs :muscle:

### CODE REVIEW

**Comment by cbeyer** [comment]
Hi, should this update be included in a new repo version ?
I'm using rector/rector 1.01 and it seems this update is not included.

I am trying to migrate my old Doctrine YAML files to attributes without success, I have found no example or doc about this

**Comment by TomasVotruba** [comment]
Hi, try `dev-main` if this rule is not in 1.0.1

We're still testing it, before putting to the docs. But you can figure out the configuration from `configure()` method of this rule :+1:

**Comment by TomasVotruba** [comment]
You can use the rule itself:

```php
return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ])
    ->withConfiguredRule(YamlToAttributeDoctrineMappingRector::class, [
        __DIR__ . '/Resources/config/doctrine/',
    ]);
```

**Comment by cbeyer** [comment]
Thanks. I tried this, but it does nothing :/

```
use Rector\Doctrine\CodeQuality\Rector\Class_\YamlToAttributeDoctrineMappingRector;

(...)

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/src/MyBundle1/Entity/',
    ])
    ->withConfiguredRule(YamlToAttributeDoctrineMappingRector::class, [
        __DIR__ . '/config/doctrine/MyBundle1/',
    ])
;
```

After executing, Rector displays "[OK] Rector is done!" but no file is modified and no progress bar is shown. What is wrong ?

**Comment by TomasVotruba** [comment]
We'll need a reproducer repository, to see where the issue is.

**Comment by cbeyer** [comment]
I have a Symfony (now 6.4) project, with code cut into "bundles". Here a example with one entity in one of my home-made-bundle.

Properties are declarated in /config/doctrine/Alert/Alerte.orm.yml :

```yaml
App\Alert\Entity\Alerte:
    type: entity
    table: alerte_alerte
    repositoryClass: App\Alert\Repository\AlerteRepository

    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
```

The equivalent entity is defined with the other PHP code, in src/Alert/Entity/Alerte.php :

```php

namespace App\Alert\Entity;

use Symfony\Component\Validator\Constraints as Assert;

class Alerte
{
    /**
     * @var int
     */
    private $id;

    (...) getters/setters
}

```

And Doctrine configuration, in config/packages/doctrine.yaml :

```yaml
doctrine:
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        auto_mapping: true

        mappings:

            Alert:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/Alert'
                prefix: 'App\Alert\Entity'

```

My rector.php :

```php


declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Doctrine\CodeQuality\Rector\Class_\YamlToAttributeDoctrineMappingRector;

return RectorConfig::configure()

    ->withPaths([
        __DIR__ . '/src/Alert/Entity/',
    ])

    ->withConfiguredRule(YamlToAttributeDoctrineMappingRector::class, [
        __DIR__ . '/config/doctrine/Alert/',
    ])

;
```

I have tried multiple times, with multiple folders, nothing happens :/

**Pull request merged**
