### PR TITLE
Adapt testcase for changes in rectorphp/rector-src#2699

### PR DESCRIPTION
**Pull request by acrobat**
Related to rectorphp/rector-src#2699

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks :+1: 

Could you require the fix branch https://github.com/rectorphp/rector-src/pull/2699, so we can see if test are passing here?

**Comment by acrobat** [comment]
@TomasVotruba you mean that I add my fork here a composer repostory and switch `rector/rector-src` to my fork branch?

**Comment by TomasVotruba** [comment]
> you mean that I add my fork here a composer repostory and switch rector/rector-src to my fork branch?

Yes, I think you can just require the commit hash from PR.

```json
{
    "require": {
       `"rector/rector-src": "dev-main#hash"
    }
}
```

**Comment by acrobat** [comment]
@TomasVotruba done 👌

**Comment by TomasVotruba** [comment]
Thanks, that's all we need :+1: 

It does not block each other, so I'm going to merge both now.
When you have time tomorrow, please send "cleaning" PR to remove it.

Thank you

**Pull request merged**
