### PR TITLE
Fix TypedPropertyFromToManyRelationTypeRector with no property

### PR DESCRIPTION
**Pull request by TomasVotruba**
Fixes https://github.com/rectorphp/rector-doctrine/pull/76

- Dont Touch Unrelated Code by TypedPropertyFromToManyRelationTypeRector unit test
- Fix empty typed property in TypedPropertyFromToManyRelationTypeRector

### CODE REVIEW

**Comment by PhilETaylor** [comment]
hmm - what's the process for this merging up to rector?

I have updated and have Rector 1c7460bcfc2201edd90ab0e7bae066ed53980b2f and Im still getting some issues...

**Comment by TomasVotruba** [comment]
Was that version released after this got merged? It's always all `dev-main` version of split packages.

Some issue or the same issue?

**Comment by PhilETaylor** [comment]
Pretty much the same issue

vendor/bin/rector -V
Rector 1c7460bcfc2201edd90ab0e7bae066ed53980b2f

**Comment by samsonasik** [comment]
@PhilETaylor after merged, it needs wait for at least 7-8 minutes to downgrade https://github.com/rectorphp/rector/commit/7a85fbdbd8ef5cd0ab423241d76d430d88444369 

Please run `composer update` again

**Comment by PhilETaylor** [comment]
composer updated and now on  rector/rector: 'dev-main#7a85fbdbd8ef5cd0ab423241d76d430d88444369' 

That fixed it ! thanks. :) 

Sorry to be on the bleeding edge, not expecting instant help/replies, just trying to help :)

**Pull request merged**
