### PR TITLE
Update rector_rules_overview.md. Remove repeated `TypedPropertyFromToOneRelationTypeRector` rule.

### PR DESCRIPTION
**Pull request by bdaler**
The `TypedPropertyFromToOneRelationTypeRector` rule was repeated.

### CODE REVIEW

**Comment by samsonasik** [comment]
You can run:

```
composer docs
```

instead of manually check for it.

**Comment by bdaler** [comment]
> You can run:
> 
> ```
> composer docs
> ```
> 
> instead of manually check for it.

Sorry, but I didn't get you, could you please explain it please?

**Comment by samsonasik** [comment]
You can run the following command:

```
composer update
composer docs
```

then the docs will be regenerated. Then, you can commit the change.

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
